### ISSUE TITLE
Send raw buffers using whisper and shout

### ISSUE THREAD

**Issue by Dev1an** [interpretor/zyre.js#5]
If I understand it correctly [your API](../blob/e62f7709dd03dc69b3e024f13edad8c7277c4cf4/lib/zyre.js#L162) allows us only to send `String` messages.

Is it also possible to whisper raw buffers to other zyre peers?

**Comment by interpretor** [comment]
Yes, it's possible.
I am already testing it in [binary-messages](https://github.com/interpretor/zyre.js#binary-messages). I am just not sure about usability, because if I change the API, a `console.log(msg)` will result in a `<Buffer 61 73 64 66>`. You would have to use `console.log(msg.toString())` to read `string` messages.
Sending messages would be no problem, as `zyre.whisper()` and `zyre.shout()` accept raw buffers as well.

If you want to test raw buffers now on your side, you could add `"zyre.js": "interpretor/zyre.js#binary-messages"` as a dependency in `package.json`.
Let me know how you think about it, and then we could add this in a new release.

**Comment by Dev1an** [comment]
OK so maybe you can use the same api as the [Readable Stream](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_stream). So that you can change the encoding of messages using a method [.setEncoding(encoding)](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_readable_setencoding_encoding).

If you then want your new API to be backwards compatible with the current one, you could set the default encoding to `"utf8"`. And users that need raw buffer access can simply call `Zyre#setEncoding(null)`, an API they are already comfortable with since this is the common way to this in NodeJS API's.

**Comment by interpretor** [comment]
Good idea! I will look into this and update the binary-messages branch.
Would be great if you test it when it's updated.

**Comment by Dev1an** [comment]
Sure, I would be happy to test it!

And thanks for your nice API, it makes things way simpler than trying to use the official NodeJS Zyre binding 🙂.

**Comment by interpretor** [comment]
I pushed a commit which adds support for multiple encodings plus the possibility to receive raw Buffers. https://github.com/interpretor/zyre.js/commit/414f28a139d17af55b9aa0cbd6d15f8edca23cbf

**Comment by interpretor** [comment]
@Dev1an could you already test it? I can merge this to master for the next minor release if it works.

**Comment by interpretor** [comment]
Merged to `master`
